# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import talia_pb2 as talia__pb2


class TaliaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Summarize = channel.unary_unary(
                '/talia.TaliaService/Summarize',
                request_serializer=talia__pb2.SummarizeRequest.SerializeToString,
                response_deserializer=talia__pb2.SummarizeResponse.FromString,
                )
        self.Classify = channel.unary_unary(
                '/talia.TaliaService/Classify',
                request_serializer=talia__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=talia__pb2.ClassifyResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/talia.TaliaService/HealthCheck',
                request_serializer=talia__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=talia__pb2.HealthCheckResponse.FromString,
                )


class TaliaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Summarize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Classify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaliaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Summarize': grpc.unary_unary_rpc_method_handler(
                    servicer.Summarize,
                    request_deserializer=talia__pb2.SummarizeRequest.FromString,
                    response_serializer=talia__pb2.SummarizeResponse.SerializeToString,
            ),
            'Classify': grpc.unary_unary_rpc_method_handler(
                    servicer.Classify,
                    request_deserializer=talia__pb2.ClassifyRequest.FromString,
                    response_serializer=talia__pb2.ClassifyResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=talia__pb2.HealthCheckRequest.FromString,
                    response_serializer=talia__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'talia.TaliaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TaliaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Summarize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/talia.TaliaService/Summarize',
            talia__pb2.SummarizeRequest.SerializeToString,
            talia__pb2.SummarizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Classify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/talia.TaliaService/Classify',
            talia__pb2.ClassifyRequest.SerializeToString,
            talia__pb2.ClassifyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/talia.TaliaService/HealthCheck',
            talia__pb2.HealthCheckRequest.SerializeToString,
            talia__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
